# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "083612a10536c5adc420f1bda9d147c6"
name = "suppplier qty perastore"
application_url = "https://suppplier-qty-perastore-1a3c3184fb6a.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://suppplier-qty-perastore-1a3c3184fb6a.herokuapp.com/api/auth" ]
