# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "76ffd6478baa6da15a8cc1055c5c4d64"
name = "App-Supplier-Quantity"
handle = "deepak-supplier-quantity"
application_url = "https://tape-pop-nova-lambda.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_themes,write_customers,write_inventory,write_products,write_publications,write_themes"

[auth]
redirect_urls = ["https://tape-pop-nova-lambda.trycloudflare.com/auth/callback", "https://tape-pop-nova-lambda.trycloudflare.com/auth/shopify/callback", "https://tape-pop-nova-lambda.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[app_preferences]
url = "https://supplier-quantity-71088c98616f.herokuapp.com/"

[build]
automatically_update_urls_on_dev = true
